name: foodgram-ui-tests

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull browser image
        run: docker pull selenoid/chrome:128.0

      - name: Run tests in Docker Compose
        run: docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Stop containers
        if: always()
        run: docker compose down -v
